Service/list-routes
Pis-moove-it/reciclando-backend pull request #136
Opened 2018-10-27 20:28 UTC by GonzaNunezCano

### Brief Description
 The service is available to list all the existing routes of an organization 
### Related card or ticket
-- Add here a link to the related card or ticket --
https://github.com/Pis-moove-it/reciclando-backend/issues/35

2018-10-27 20:49 UTC, gastonabella requested changes

2018-10-27 20:49 UTC, gastonabella commented on public/docs/swagger.yaml
>          200:
Here you are not listing the routes in an array, as in  200 OK responses in other GET services

2018-10-27 20:49 UTC, gastonabella commented on public/docs/swagger.yaml
> +        type: object
Here you can replace `object` with `'#/definitions/User'`, and not defining the User again

2018-10-28 22:37 UTC, fbalarini commented on app/controllers/base_controller.rb
> +      count = query.count
Repeated code

2018-10-28 22:37 UTC, fbalarini commented on app/controllers/base_controller.rb
> +      page_count = (count / per_page.to_f).ceil
What do you think about moving this to another method? I think this logic is making this method more difficult to understand. What's more, maybe we can set `total_pages` to be 1 as default and use mod `%` operator when `count > per_page`.

2018-10-29 22:34 UTC, fbalarini approved these changes

2018-10-29 22:43 UTC, gastonabella approved these changes

2018-10-29 23:07 UTC, merged