admin can edit recycled materials kg
Pis-moove-it/reciclando-backend pull request #137
Opened 2018-10-28 16:15 UTC by accg14

### Brief Description
Admin is able to load values of kgs recycled material.
### Related card or ticket
https://github.com/orgs/Pis-moove-it/projects/8#card-14188942
### Additional Details
Schema was updated, migrations are required.

2018-10-28 18:48 UTC, GonzaNunezCano requested changes

2018-10-28 18:48 UTC, GonzaNunezCano commented on app/admin/collection_points.rb
> +ActiveAdmin.register CollectionPoint do
Remove the fields created_at and updated_at from the filters and the form.

2018-10-28 22:18 UTC, fbalarini requested changes

2018-10-28 22:18 UTC, fbalarini commented on app/admin/collection_points_map.rb
> +ActiveAdmin.register_page 'CollectionPoints' do
Did you check that the map is working as expected? I believe that you also need to change views file name

2018-10-28 22:18 UTC, fbalarini commented on app/admin/collection_points.rb
> +  # end
Remove this commented code

2018-10-29 20:39 UTC, fbalarini approved these changes

2018-11-02 22:43 UTC, GonzaNunezCano approved these changes

2018-11-02 22:49 UTC, merged