Add pocket
Pis-moove-it/reciclando-backend pull request #81
Opened 2018-10-02 21:00 UTC by gastonabella

### Brief Description
Add pocket service for frontend.
### Related card or ticket
https://github.com/Pis-moove-it/reciclando-backend/issues/10
### Additional Details
Given a route_id, a collection_point_id and an array of pocket_serial_numbers, it creates a Collection associated to the ids mentioned, and create pockets with the serial numbers given associated to the collection too.
- Service for frontend
- Controller tests
- Swagger service
- Fixtures done for routes and collection points

2018-10-02 22:02 UTC, fbalarini requested changes

2018-10-02 22:02 UTC, fbalarini commented on config/routes.rb
> +  resources :routes, only: [] do
Duplicated

2018-10-02 22:02 UTC, fbalarini commented on db/seeds.rb
> +
remove this whitespace

2018-10-02 22:02 UTC, fbalarini commented on spec/controllers/bales_controller_spec.rb
> +        create_bale_call(nil, bale.material)
why?

2018-10-02 22:02 UTC, fbalarini commented on spec/factories/collection_points.rb
> +    latitude { Faker::Number.decimal(2, 6) }
mmm, Faker doesn't have a method for longitude and latitude ?

2018-10-02 22:02 UTC, fbalarini commented on app/controllers/collections_controller.rb
> +    serials = params[:collection][:pocket_serial_numbers]
maybe it is better to get this from a private method in this controller

2018-10-02 22:02 UTC, fbalarini commented on app/controllers/collections_controller.rb
> +    collection.pockets.new(pockets)
Research about `nested_attributes`. It is possible to make this easier, if pockets is accepted as a nested attribute for collections, you can create them by putting pockets params inside collection params. If you don't get my point, let me know and we discuss it.

2018-10-03 00:01 UTC, gastonabella commented on spec/controllers/bales_controller_spec.rb
> +        create_bale_call(nil, bale.material)
This is an error of an old feature and I fix it as soon as I noticed it. Perhaps this should have been done in other PR.

2018-10-05 22:08 UTC, closed without merging